from typing import Protocol
from emotv.domain.activity import Activity


class ActivityRepository(Protocol):
    def get_by_id(self, activity_id: str) -> Activity | None: ...
    def list_all(self) -> tuple[Activity, ...]: ...
    def add(self, activity: Activity) -> Activity: ...
    def update(self, activity: Activity) -> Activity: ...
    def remove(self, activity_id: str) -> Activity: ...
