from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Protocol


@dataclass(frozen=True, slots=True)
class StoredChatMessage:
    role: str
    content: str
    in_scope: bool | None
    category: str | None
    created_at: datetime


class ChatRepository(Protocol):
    """Persistencia de las conversaciones de Emi."""

    def create_conversation(self, user_id: str, at: datetime) -> str: ...
    def latest_conversation(self, user_id: str) -> str | None: ...
    def owns(self, conversation_id: str, user_id: str) -> bool: ...
    def list_messages(self, conversation_id: str, limit: int) -> list[StoredChatMessage]: ...
    def recent_in_scope(self, conversation_id: str, limit: int) -> list[StoredChatMessage]: ...
    def count_user_messages(self, user_id: str, since: datetime) -> int: ...
    def add_user_message(self, conversation_id: str, content: str, at: datetime) -> int: ...
    def complete_exchange(self, user_message_id: int, conversation_id: str, answer: str,
                          in_scope: bool, category: str, at: datetime) -> None: ...
    def record_rejection(self, category: str, at: datetime) -> None: ...
    def purge(self, before: datetime, include_conversations: bool = True) -> int: ...
