from typing import Protocol, runtime_checkable

from emotv.domain.consent import ConsentRecord


@runtime_checkable
class ConsentRepository(Protocol):
    def save(self, consent: ConsentRecord) -> ConsentRecord: ...
    def get_by_id(self, consent_id: str) -> ConsentRecord | None: ...
    def list_by_student(self, student_id: str) -> tuple[ConsentRecord, ...]: ...
    def get_active_by_student(self, student_id: str) -> ConsentRecord | None: ...
