from typing import Protocol, runtime_checkable

from emotv.domain.user import Student


@runtime_checkable
class StudentRepository(Protocol):
    def save(self, student: Student) -> Student: ...
    def get_by_id(self, student_id: str) -> Student | None: ...
    def get_by_user_id(self, user_id: str) -> Student | None: ...
    def get_by_code(self, student_code: str) -> Student | None: ...
    def list_all(self) -> tuple[Student, ...]: ...
