from typing import Protocol, runtime_checkable

from emotv.domain.user import User


@runtime_checkable
class UserRepository(Protocol):
    def save(self, user: User) -> User: ...
    def get_by_id(self, user_id: str) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def list_all(self) -> tuple[User, ...]: ...
